plugins {
    id "com.android.application"
}

configurations.all {
    resolutionStrategy.eachDependency { details ->
        if (details.requested.group == "org.jetbrains.kotlin") {
            details.useVersion "1.9.24"
            details.because "align kotlin-stdlib / jdk7 / jdk8 for biometric"
        }
    }
}

android {
    namespace "app.kysmindset.security"
    compileSdk 35
    defaultConfig {
        applicationId "app.kysmindset.security"
        minSdk 26
        targetSdk 35
        versionCode 3
        versionName "2.1.0"
    }
    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation "androidx.webkit:webkit:1.12.1"
    implementation "androidx.core:core:1.15.0"
    implementation "androidx.appcompat:appcompat:1.7.0"
    implementation "androidx.biometric:biometric:1.1.0"
}
